// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrxvLZtz5Qq8p4agX6lJSOKwUe2UugtAA',
    appId: '1:547794696661:web:c25ed5c3be56675e55e55c',
    messagingSenderId: '547794696661',
    projectId: 'expenses-tracker-641c3',
    authDomain: 'expenses-tracker-641c3.firebaseapp.com',
    storageBucket: 'expenses-tracker-641c3.firebasestorage.app',
    measurementId: 'G-ZFKVLSY3BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyGT8ECbQRlmWstGSTxkOq-OFKlRG1Pk',
    appId: '1:547794696661:android:496e126d801a6bae55e55c',
    messagingSenderId: '547794696661',
    projectId: 'expenses-tracker-641c3',
    storageBucket: 'expenses-tracker-641c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5_bGWbdwchWyRbMq_ANVKuwUPQ2rOmw',
    appId: '1:547794696661:ios:4d72b77935ab2c7055e55c',
    messagingSenderId: '547794696661',
    projectId: 'expenses-tracker-641c3',
    storageBucket: 'expenses-tracker-641c3.firebasestorage.app',
    iosBundleId: 'com.codeforany.trackizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5_bGWbdwchWyRbMq_ANVKuwUPQ2rOmw',
    appId: '1:547794696661:ios:4d72b77935ab2c7055e55c',
    messagingSenderId: '547794696661',
    projectId: 'expenses-tracker-641c3',
    storageBucket: 'expenses-tracker-641c3.firebasestorage.app',
    iosBundleId: 'com.codeforany.trackizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrxvLZtz5Qq8p4agX6lJSOKwUe2UugtAA',
    appId: '1:547794696661:web:ff33821704ec979c55e55c',
    messagingSenderId: '547794696661',
    projectId: 'expenses-tracker-641c3',
    authDomain: 'expenses-tracker-641c3.firebaseapp.com',
    storageBucket: 'expenses-tracker-641c3.firebasestorage.app',
    measurementId: 'G-T9VF8484GY',
  );
}
